### ISSUE TITLE
Fix: Application crashing on entering Coins Detail second time

### ISSUE THREAD

**Issue by kaungkhantsoe** [nimblehq/jetpack-compose-crypto#92]
## Issue

Application is crashing on second attempt of entering `Detail Screen`.

https://user-images.githubusercontent.com/32578035/216288358-cc4c5ea2-2017-4ab8-96ce-1478034a83dc.mov

## Expected

Application should not crash when we enter `Detail Screen`.

## Steps to reproduce

1. Go to `Home Screen`
2. Click on any coin to go to `Detail Screen`
3. Go back
4. Click on the same coin to to `Detail Screen`

**Comment by luongvo** [comment]
@kaungkhantsoe Do you have the crash log?

**Comment by kaungkhantsoe** [comment]
Here is the crash log @luongvo 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.nimblehq.compose.crypto, PID: 19968
    java.util.NoSuchElementException
        at co.nimblehq.compose.crypto.ui.components.linechart.CoinPriceChartKt$CoinPriceChart$3.invoke(CoinPriceChart.kt:88)
        at co.nimblehq.compose.crypto.ui.components.linechart.CoinPriceChartKt$CoinPriceChart$3.invoke(CoinPriceChart.kt:47)
        at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:104)
        at androidx.compose.ui.node.BackwardsCompatNode.draw(BackwardsCompatNode.kt:381)
        at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:92)
        at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:371)
        at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
        at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
        at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
        at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
        at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
        at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
        at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
        at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:840)
        at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
        at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
        at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
        at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:397)
        at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:396)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2139)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:130)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:126)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
        at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:396)
        at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:58)
        at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:180)
        at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:298)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1010)
        at android.view.View.draw(View.java:23901)
        at android.view.View.updateDisplayListIfDirty(View.java:22767)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
        at android.view.View.updateDisplayListIfDirty(View.java:22714)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
        at android.view.View.updateDisplayListIfDirty(View.java:22714)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:22714)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
        at android.view.View.updateDisplayListIfDirty(View.java:22714)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:5445)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5153)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4217)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2924)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10513)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
        at android.view.Choreographer.doCallbacks(Choreographer.java:866)
        at android.view.Choreographer.doFrame(Choreographer.java:797)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
I have also fixed it at [this PR](https://github.com/nimblehq/jetpack-compose-crypto/pull/93)
